const en = {
  hero: {
    eyebrow: "IDRAK AI Solutions · Oman",
    titleA: "AI That Creates",
    titleB: "Business Value.",
    intro:
      "We turn AI capabilities into practical solutions that help businesses increase sales, reduce costs, and improve everyday performance.",
    support: ["Less manual work.", "Better sales follow-up.", "Clearer product value."],
    chips: ["More sales", "Lower costs", "Better performance"],
    imageAlt: "The IDRAK ribbon as a glowing glass sculpture",
    scroll: "Scroll",
  },
  ticker: [
    "AI Agents",
    "WhatsApp Sales Automation",
    "Custom Business Software",
    "AI Video Production",
    "Content Engines",
    "Web, SEO & GEO",
    "CRM & Follow-up",
    "Ready-made Products",
  ],
  statement: {
    eyebrow: "AI for real business",
    text: "Beyond the AI hype. AI matters when it creates a visible result inside the business: more sales, lower costs and better performance.",
    outcomes: [
      {
        title: "More Sales",
        text: "Better follow-up, stronger customer journeys and clearer opportunities.",
      },
      { title: "Lower Costs", text: "Less repetitive work and more efficient business processes." },
      {
        title: "Better Performance",
        text: "Connected information, faster execution and smarter workflows.",
      },
    ],
  },
  solutions: {
    eyebrow: "Our solutions",
    title: "One team. Five ways to create value.",
    intro:
      "We start with the business need, then choose the right mix of AI, automation, content and digital tools.",
    more: "Explore all solutions",
    tabs: [
      {
        key: "automation",
        label: "Business Automation",
        title: "Software built around the way you work.",
        text: "Custom systems around your real workflows, teams and processes — built faster with AI, without forcing your company into unnecessary complexity.",
        points: [
          "Less manual work, faster operations",
          "Connected information and custom processes",
          "For medium and large companies",
        ],
        cta: "Discuss an Automation Project",
        href: "/contact?interest=automation",
        image: "automation",
      },
      {
        key: "whatsapp",
        label: "WhatsApp AI Sales",
        title: "Turn WhatsApp chats into an organised sales flow.",
        text: "An AI assistant answers, introduces products, captures requests, updates your CRM and follows up — and hands over to your team when a human is needed.",
        points: [
          "Replies instantly, 24/7",
          "Every conversation lands in your CRM",
          "Consistent follow-up, fewer lost leads",
        ],
        cta: "Explore WhatsApp Automation",
        href: "/services#whatsapp",
        image: "whatsapp",
      },
      {
        key: "video",
        label: "AI Video",
        title: "Show the experience of owning your product.",
        text: "Advertising storytelling and cinematic visuals that make product value tangible — even before it can be filmed.",
        points: [
          "Real estate & off-plan projects",
          "Luxury, healthcare, hotels & interiors",
          "Less reliance on actors, locations and sets",
        ],
        cta: "Discuss an AI Video",
        href: "/contact?interest=ai-video",
        image: "aiVideo",
      },
      {
        key: "content",
        label: "Content & Social",
        title: "Turn attention into an ongoing brand relationship.",
        text: "From ideas and AI-assisted production to publishing and managing your presence — each message chosen around your product, audience and commercial goal.",
        points: [
          "Ideation → production → publishing",
          "More varied ideas, distinctive campaigns",
          "Strategy still leads, AI accelerates",
        ],
        cta: "Explore Content Services",
        href: "/services#content",
        image: "content",
      },
      {
        key: "web",
        label: "Web, SEO & GEO",
        title: "A clear path from search to enquiry.",
        text: "Engaging websites aligned with your brand, found in search engines and in AI-generated answers — built to turn visits into calls and orders.",
        points: [
          "Fast, interactive web design",
          "SEO for search engines",
          "GEO for ChatGPT-style answers",
        ],
        cta: "Discuss Your Website",
        href: "/contact?interest=web",
        image: "web",
      },
    ],
  },
  products: {
    eyebrow: "Ready-made products",
    title: "Built once. Ready to deploy.",
    intro:
      "Products for needs that many businesses share — faster to start, priced around real use.",
    cta: "Explore IDRAK Products",
    items: [
      {
        tag: "Product 01",
        title: "Construction Supervision Reporting",
        subtitle: "A ready-to-deploy product for Oman",
        points: ["System deployment", "Initial staff training", "Pay per report produced"],
        href: "/products#construction-reporting",
        image: "construction",
      },
      {
        tag: "Product 02",
        title: "Clinic CRM & WhatsApp Assistant",
        subtitle: "From the first question to booking, attendance and follow-up",
        points: [
          "Answers, bookings and reminders on WhatsApp",
          "Every interaction recorded in the CRM",
          "Feedback, reviews and missed-visit follow-up",
        ],
        href: "/products#clinic-crm",
        image: "clinic",
      },
    ],
  },
  work: {
    eyebrow: "Selected work",
    title: "Digital projects we’ve delivered",
    cta: "View All Work",
  },
  demo: {
    eyebrow: "Proof, not promises",
    title: "We don’t just talk about AI. Talk to ours.",
    text: "The assistant on this site is built by IDRAK. Ask it anything about your business — the same technology can answer your customers on WhatsApp, day and night.",
    cta: "Chat with IDRAK AI",
    ask: "How can AI help a business like mine?",
    label: "Example · WhatsApp assistant for a retail store",
    chat: [
      { role: "customer", text: "Hi, do you have this rug in a bigger size? 📷" },
      {
        role: "ai",
        text: "Beautiful choice! This design comes in 2×3 and 3×4. Which size suits your room?",
      },
      { role: "customer", text: "3×4 please" },
      {
        role: "ai",
        text: "It’s available ✓ I’ve noted your request — a colleague will confirm price and delivery with you now.",
      },
    ],
  },
  founder: {
    eyebrow: "Founder & CEO",
    name: "Mohammadreza Zakeri",
    role: "Founder & CEO, IDRAK AI Solutions · Based in Oman",
    text: "We focus on the commercial, results-driven use of AI in real markets. We start with the business problem and build solutions that become part of everyday work.",
    quoteA: "AI attracts attention.",
    quoteB: "The right application creates value.",
    cta: "About Mohammadreza & IDRAK",
    imageAlt: "Portrait of Mohammadreza Zakeri, Founder & CEO of IDRAK AI Solutions",
  },
  how: {
    eyebrow: "How we work",
    title: "Start with the problem. Build what creates value.",
    steps: [
      {
        title: "Understand",
        text: "The business problem, workflow, customer journey or commercial goal.",
      },
      { title: "Define", text: "The smallest useful solution, pilot or initial deployment." },
      { title: "Build & Deploy", text: "Around real business use and the people who will use it." },
      { title: "Expand", text: "Measure results and expand what creates more value." },
    ],
    note: "Collaboration can begin with a pilot, an initial deployment or usage-based payment.",
  },
  final: {
    eyebrow: "Start with your business",
    title: "Ready to boost your business?",
    text: "Answer four quick questions. We’ll review your challenge and reach out on WhatsApp with the most practical next step.",
  },
};

export type HomeCopy = typeof en;

const ar: HomeCopy = {
  hero: {
    eyebrow: "إدراك للحلول الذكية · عُمان",
    titleA: "ذكاء اصطناعي",
    titleB: "يصنع قيمة لعملك.",
    intro:
      "نحوّل قدرات الذكاء الاصطناعي إلى حلول عملية تساعد الشركات على زيادة المبيعات وخفض التكاليف وتحسين الأداء اليومي.",
    support: ["عمل يدوي أقل.", "متابعة مبيعات أفضل.", "قيمة منتج أوضح."],
    chips: ["مبيعات أكثر", "تكاليف أقل", "أداء أفضل"],
    imageAlt: "شريط إدراك كمنحوتة زجاجية متوهجة",
    scroll: "مرّر",
  },
  ticker: [
    "وكلاء ذكاء اصطناعي",
    "أتمتة المبيعات عبر واتساب",
    "برمجيات أعمال مخصّصة",
    "فيديو بالذكاء الاصطناعي",
    "محركات المحتوى",
    "الويب وSEO وGEO",
    "CRM والمتابعة",
    "منتجات جاهزة",
  ],
  statement: {
    eyebrow: "ذكاء اصطناعي للأعمال الحقيقية",
    text: "أبعد من ضجة الذكاء الاصطناعي. تظهر قيمته عندما يصنع نتيجة ملموسة داخل العمل: مبيعات أكثر، وتكاليف أقل، وأداء أفضل.",
    outcomes: [
      { title: "مبيعات أكثر", text: "متابعة أفضل، ورحلة عميل أقوى، وفرص أوضح." },
      { title: "تكاليف أقل", text: "عمل متكرر أقل وعمليات أكثر كفاءة." },
      { title: "أداء أفضل", text: "معلومات مترابطة، وتنفيذ أسرع، وسير عمل أذكى." },
    ],
  },
  solutions: {
    eyebrow: "حلولنا",
    title: "فريق واحد. خمس طرق لصنع القيمة.",
    intro:
      "نبدأ من حاجة العمل، ثم نختار المزيج المناسب من الذكاء الاصطناعي والأتمتة والمحتوى والأدوات الرقمية.",
    more: "استكشف جميع الحلول",
    tabs: [
      {
        key: "automation",
        label: "أتمتة الأعمال",
        title: "برمجيات مبنية حول طريقة عملك.",
        text: "أنظمة مخصّصة حول سير عملك وفرقك وعملياتك الفعلية — تُبنى أسرع بالذكاء الاصطناعي، دون تعقيد لا داعي له.",
        points: [
          "عمل يدوي أقل وعمليات أسرع",
          "معلومات مترابطة وعمليات مخصّصة",
          "للشركات المتوسطة والكبيرة",
        ],
        cta: "ناقش مشروع أتمتة",
        href: "/contact?interest=automation",
        image: "automation",
      },
      {
        key: "whatsapp",
        label: "مبيعات واتساب الذكية",
        title: "حوّل محادثات واتساب إلى مسار مبيعات منظّم.",
        text: "مساعد ذكي يرد ويعرّف بالمنتجات ويسجّل الطلبات ويحدّث CRM ويتابع — ويحيل المحادثة إلى فريقك عند الحاجة إلى شخص.",
        points: [
          "رد فوري على مدار الساعة",
          "كل محادثة تصل إلى CRM",
          "متابعة منتظمة وفرص ضائعة أقل",
        ],
        cta: "استكشف أتمتة واتساب",
        href: "/services#whatsapp",
        image: "whatsapp",
      },
      {
        key: "video",
        label: "فيديو بالذكاء الاصطناعي",
        title: "اعرض تجربة امتلاك منتجك.",
        text: "سرد إعلاني ومشاهد سينمائية تجعل قيمة المنتج ملموسة — حتى قبل أن يصبح تصويره ممكناً.",
        points: [
          "المشاريع العقارية والبيع على الخارطة",
          "الفخامة والرعاية الصحية والفنادق والديكور",
          "اعتماد أقل على الممثلين ومواقع التصوير",
        ],
        cta: "ناقش فيديو بالذكاء الاصطناعي",
        href: "/contact?interest=ai-video",
        image: "aiVideo",
      },
      {
        key: "content",
        label: "المحتوى والتواصل",
        title: "حوّل الانتباه إلى علاقة مستمرة مع علامتك.",
        text: "من الأفكار والإنتاج بمساعدة الذكاء الاصطناعي إلى النشر وإدارة حضورك — كل رسالة مختارة حول منتجك وجمهورك وهدفك التجاري.",
        points: [
          "الفكرة ← الإنتاج ← النشر",
          "أفكار أكثر تنوعاً وحملات مميّزة",
          "الاستراتيجية تقود والذكاء الاصطناعي يسرّع",
        ],
        cta: "استكشف خدمات المحتوى",
        href: "/services#content",
        image: "content",
      },
      {
        key: "web",
        label: "الويب وSEO وGEO",
        title: "طريق واضح من البحث إلى الاستفسار.",
        text: "مواقع جذابة متوافقة مع علامتك، تظهر في محركات البحث وفي إجابات الذكاء الاصطناعي — مصمّمة لتحويل الزيارات إلى اتصالات وطلبات.",
        points: [
          "تصميم ويب سريع وتفاعلي",
          "SEO لمحركات البحث",
          "GEO لإجابات مساعدات الذكاء الاصطناعي",
        ],
        cta: "ناقش موقعك الإلكتروني",
        href: "/contact?interest=web",
        image: "web",
      },
    ],
  },
  products: {
    eyebrow: "منتجات جاهزة",
    title: "صُنعت مرة واحدة. جاهزة للتشغيل.",
    intro: "منتجات لاحتياجات تتشاركها شركات كثيرة — بداية أسرع وتسعير وفق الاستخدام الفعلي.",
    cta: "استكشف منتجات إدراك",
    items: [
      {
        tag: "المنتج 01",
        title: "نظام تقارير الإشراف على البناء",
        subtitle: "منتج جاهز للتشغيل في عُمان",
        points: ["تشغيل النظام", "تدريب أوّلي للفريق", "الدفع مقابل كل تقرير"],
        href: "/products#construction-reporting",
        image: "construction",
      },
      {
        tag: "المنتج 02",
        title: "نظام CRM ومساعد واتساب للعيادات",
        subtitle: "من أول سؤال إلى الحجز والحضور والمتابعة",
        points: [
          "ردود وحجوزات وتذكيرات عبر واتساب",
          "كل تفاعل مسجّل في CRM",
          "تقييمات ومراجعات ومتابعة المواعيد الفائتة",
        ],
        href: "/products#clinic-crm",
        image: "clinic",
      },
    ],
  },
  work: {
    eyebrow: "أعمال مختارة",
    title: "مشاريع رقمية نفّذناها",
    cta: "عرض جميع الأعمال",
  },
  demo: {
    eyebrow: "دليل لا وعود",
    title: "لا نتحدث عن الذكاء الاصطناعي فقط. تحدّث مع ذكائنا.",
    text: "المساعد على هذا الموقع من بناء إدراك. اسأله أي شيء عن عملك — التقنية نفسها يمكنها الرد على عملائك عبر واتساب ليلاً ونهاراً.",
    cta: "تحدّث مع مساعد إدراك",
    ask: "كيف يمكن للذكاء الاصطناعي أن يساعد عملاً مثل عملي؟",
    label: "مثال · مساعد واتساب لمتجر تجزئة",
    chat: [
      { role: "customer", text: "مرحباً، هل عندكم هذا السجاد بمقاس أكبر؟ 📷" },
      { role: "ai", text: "اختيار رائع! هذا التصميم متوفر بمقاس 2×3 و3×4. أي مقاس يناسب غرفتك؟" },
      { role: "customer", text: "3×4 لو سمحت" },
      { role: "ai", text: "متوفر ✓ سجّلت طلبك — سيؤكد لك زميلي السعر وموعد التوصيل الآن." },
    ],
  },
  founder: {
    eyebrow: "المؤسس والرئيس التنفيذي",
    name: "محمد رضا ذاكري",
    role: "المؤسس والرئيس التنفيذي، إدراك للحلول الذكية · مقيم في عُمان",
    text: "نركّز على الاستخدام التجاري للذكاء الاصطناعي الموجّه نحو النتائج في الأسواق الحقيقية. نبدأ من مشكلة العمل ونبني حلولاً تصبح جزءاً من العمل اليومي.",
    quoteA: "الذكاء الاصطناعي يجذب الانتباه.",
    quoteB: "والتطبيق الصحيح يصنع القيمة.",
    cta: "تعرّف على محمد رضا وإدراك",
    imageAlt: "صورة محمد رضا ذاكري، المؤسس والرئيس التنفيذي لإدراك للحلول الذكية",
  },
  how: {
    eyebrow: "كيف نعمل",
    title: "ابدأ من المشكلة. وابنِ ما يصنع القيمة.",
    steps: [
      { title: "نفهم", text: "مشكلة العمل أو سير العمل أو رحلة العميل أو الهدف التجاري." },
      { title: "نحدّد", text: "أصغر حل مفيد أو تجربة أولية أو تشغيل أوّلي." },
      { title: "نبني ونشغّل", text: "حول الاستخدام الفعلي ومن سيستخدمون الحل." },
      { title: "نوسّع", text: "نقيس النتائج ونوسّع ما يصنع قيمة أكبر." },
    ],
    note: "يمكن أن يبدأ التعاون بتجربة أولية أو تشغيل أوّلي أو دفع حسب الاستخدام.",
  },
  final: {
    eyebrow: "ابدأ من عملك",
    title: "مستعد لتعزيز أعمالك؟",
    text: "أجب عن أربعة أسئلة سريعة. سنراجع التحدي الذي تواجهه ونتواصل معك عبر واتساب بالخطوة التالية الأكثر عملية.",
  },
};

export const HOME = { en, ar };
